# docker-compose.yml (Versi Terbaik)

services:
  db:
    image: postgres:15
    container_name: my_postgres_db
    restart: always
    environment:
      # Ambil nilai dari file .env secara otomatis
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: